apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gartic-app
  annotations:
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-modsecurity-crs: "true"
    # nginx.ingress.kubernetes.io/modsecurity-snippet: |
      # SecRuleEngine On
      # SecRequestBodyAccess On
      # SecAuditLog /var/log/modsec_audit.log
    nginx.ingress.kubernetes.io/server-snippet: |
      ssl_certificate /vault/secrets/tls-cert;
      ssl_certificate_key /vault/secrets/tls-key;
spec:
  ingressClassName: nginx
  rules:
    # - host: {{ .Values.ingress.host }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gartic-app
                port:
                  number: {{ .Values.service.port }}
