{
 "title": "Trans",
 "time": { "from": "2026-04-16T09:35:53.797Z", "to": "2026-04-16T12:15:53.797Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"node-exporter\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pods Status",
   "type": "piechart",
   "description": "TO FIX\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(phase) (kube_pod_status_phase{job=\"kube-state-metrics\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", device!~\"lo|cni.*|flannel.*|veth.*\"}[5m])",
     "legendFormat": "{{node}} - {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", device!~\"lo|cni.*|flannel.*|veth.*\"}[5m])",
     "legendFormat": "{{node}} - {{device}}"
    }
   ]
  },
  {
   "title": "Pods per Node",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(node) (kube_pod_info{job=\"kube-state-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((avg by(node) (node_filesystem_avail_bytes{job=\"node-exporter\", mountpoint=\"/\", fstype!=\"tmpfs\"}) / avg by(node) (node_filesystem_size_bytes{job=\"node-exporter\", mountpoint=\"/\", fstype!=\"tmpfs\"})) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(node) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((avg by(node) (node_memory_MemAvailable_bytes{job=\"node-exporter\"}) / avg by(node) (node_memory_MemTotal_bytes{job=\"node-exporter\"})) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}