# version: '3.8'

services:
  # L'application (Front compilé + Back Go)
  app:
    build:
      context: .
      dockerfile: Dockerfile_local
    ports:
      - "8080:8080"
    environment:
      - LOCAL=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=123
      - DB_NAME=transcendence
    depends_on:
      - db
      # - prometheus
    networks:
      - monitoring
    restart: always

  # Le scanner qui envoie le code vers SonarCloud
  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: sonar-scanner
    volumes:
      - .:/usr/src
    environment:
      - SONAR_HOST_URL=https://sonarcloud.io
      - SONAR_TOKEN=${SONAR_TOKEN}
    profiles:
      - tools
  # La base de données
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=transcendence
    ports:
      - "5432:5432"
    networks:
      - monitoring
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  prometheus:
      image: prom/prometheus:latest
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus_local.yml:/etc/prometheus/prometheus.yml
      networks:
        - monitoring
      depends_on:
        - app

  grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin # Change this for production!
      networks:
        - monitoring
      depends_on:
        - prometheus
        - app
  
networks:
  monitoring:
    driver: bridge

volumes:
  postgres_data:
