CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS rooms (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	room_code VARCHAR(6) UNIQUE NOT NULL,
	status VARCHAR(50) DEFAULT 'create',
	settings JSONB NOT NULL DEFAULT '{}',
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	username VARCHAR(20) UNIQUE NOT NULL,
<<<<<<< HEAD

=======
	is_guest BOOLEAN DEFAULT FALSE,
>>>>>>> 5fe6cb6f876601e10f69acdbe2579727f8c9fe60
	is_online BOOLEAN DEFAULT FALSE
);
