services:
  vault-agent:
    image: hashicorp/vault:{{ vault_version }}
    user: "70:70"
    command: agent -config=/vault/config/agent.hcl
    environment:
      - SKIP_SETCAP=true
      - SKIP_CHOWN=true
    volumes:
      - ./agent.hcl:/vault/config/agent.hcl:ro
      - ./db_user.tpl:/vault/templates/db_user.tpl:ro
      - ./db_password.tpl:/vault/templates/db_password.tpl:ro
      - ./db_name.tpl:/vault/templates/db_name.tpl:ro
      - secrets:/secrets
      - postg_socket:/var/run/postgresql
    restart: always
    networks:
      - security_net
    extra_hosts:
      - "vault:host-gateway"
    entrypoint: >
      sh -c "chmod 700 /secrets && vault agent -config=/vault/config/agent.hcl"

  db:
    pid: service:vault-agent
    image: postgres:{{ db_version }}
    environment:
      - POSTGRES_USER_FILE=/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/secrets/db_password
      - POSTGRES_DB_FILE=/secrets/db_name
      #- POSTGRES_INITDB_ARGS=--auth-local=peer
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - secrets:/secrets:ro
      - postg_socket:/var/run/postgresql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
    networks:
      - security_net
    depends_on:
      - vault-agent
    extra_hosts:
      - "169.254.169.254:127.0.0.1"

volumes:
  postgres_data:
    driver: local
  secrets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=10m,uid=70,gid=70,mode=700"
  postg_socket:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=1m,uid=70,gid=70,mode=750"

networks:
  security_net:
    driver: bridge
