---
aws_region: eu-north-1
ecr_url: "437836833311.dkr.ecr.eu-north-1.amazonaws.com"
repo_name: "gartic-trans-app"
image_tag: "latest"
db_user: "user_test"
db_password: "password_ultra_secret_123"
db_name: "db"
db_host: "db"
app_path: "/opt/gartic-app"
app_name: "app"
vault_port: "8200"
