---
- name: "Direcory exist ?"
  file:
    path: "{{ app_path }}"
    state: directory
    mode: '0755'

- name: "Connexion to AWS"
  shell: "aws ecr get-login-password --region {{aws_region}} | docker login --username AWS --password-stdin {{ ecr_url }}"
  changed_when: false

- name: "copy docker-compose"
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_path }}/docker-compose.yml"
    mode: '0644'

- name: "pull go image from AWS"
  shell: "docker compose up -d --pull always"
  args:
    chdir: "{{ app_path }}"
