---
- name: "Directory exist ?"
  file:
    path: "{{ app_path }}"
    state: directory
    mode: '0755'

- name: "Connexion to AWS"
  shell: "aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ ecr_url }}"
  changed_when: false

- name: "Copy vault agent config"
  template:
    src: agent.hcl.j2
    dest: "{{ app_path }}/agent.hcl"
    mode: '0644'
  notify: "Restart APP"

- name: "Copy app secret template"
  template:
    src: app.tpl.j2
    dest: "{{ app_path }}/app.tpl"
    mode: '0644'
  notify: "Restart APP"

- name: "Copy db_user secret template"
  template:
    src: db_user.tpl.j2
    dest: "{{ app_path }}/db_user.tpl"
    mode: '0644'
  notify: "Restart APP"

- name: "Copy db_password secret template"
  template:
    src: db_password.tpl.j2
    dest: "{{ app_path }}/db_password.tpl"
    mode: '0644'
  notify: "Restart APP"

- name: "Copy db_name secret template"
  template:
    src: db_name.tpl.j2
    dest: "{{ app_path }}/db_name.tpl"
    mode: '0644'
  notify: "Restart APP"

- name: "Copy docker-compose"
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_path }}/docker-compose.yml"
    mode: '0644'
  notify: "Restart APP"

- name: "Pull and start containers"
  shell: "docker compose up -d --pull always"
  args:
    chdir: "{{ app_path }}"
