---
- name: "Restart Grafana"
  shell: "docker compose restart"
  args:
    chdir: "{{ grafana_path }}"
  environment:
    GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_pass }}"
    VERSION_PROMETHEUS: "{{ version_prometheus }}"
    VERSION_GRAFANA: "{{ version_grafana }}"
    VERSION_NODE_EXPORTER: "{{ version_node_exporter }}"
    PT_GRAF: "{{ pt_graf }}"
    PT_PROM: "{{ pt_prom }}"
    PT_N_E: "{{ pt_n_e }}"
