daemonset:
  enabled: true

  # TODO: Vault PKI + Cilium
  podAnnotations:
    vault.hashicorp.com/agent-inject: "false"

  extraEnvs:
    - name: "ELASTICSEARCH_USERNAME"
      valueFrom:
        secretKeyRef:
          name: elasticsearch-credentials
          key: username
    - name: "ELASTICSEARCH_PASSWORD"
      valueFrom:
        secretKeyRef:
          name: elasticsearch-credentials
          key: password

  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
        - type: container
          paths:
            - /var/log/containers/*.log
          processors:
            - add_kubernetes_metadata:
                host: ${NODE_NAME}
                matchers:
                  - logs_path:
                      logs_path: "/var/log/containers/"

        - type: log
          paths:
            - /var/log/*.log
            - /var/log/messages
            - /var/log/syslog
          fields:
            type: system
          fields_under_root: true

      processors:
        - add_cloud_metadata: ~
        - add_host_metadata: ~

      output.elasticsearch:
        hosts: ["https://elasticsearch-master.logging.svc:9200"]
        username: "${ELASTICSEARCH_USERNAME}"
        password: "${ELASTICSEARCH_PASSWORD}"
        protocol: https
        ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca.crt"]
        ssl.verification_mode: "certificate"

      logging.level: info

  secretMounts:
    - name: elasticsearch-master-certs
      secretName: elasticsearch-master-certs
      path: /usr/share/filebeat/certs/

  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "500m"
      memory: "200Mi"

  securityContext:
    runAsUser: 0
    privileged: false

  tolerations:
    - operator: Exists

deployment:
  enabled: false

imageTag: "8.5.1"

hostPathRoot: /var/lib

dnsPolicy: ClusterFirstWithHostNet

managedServiceAccount: true

clusterRoleRules:
  - apiGroups: [""]
    resources:
      - namespaces
      - nodes
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps"]
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch

updateStrategy: RollingUpdate
