serviceAccount:
  create: true
  name: grafana
  automountServiceAccountToken: true

replicas: 1

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/role: "grafana-role"
  vault.hashicorp.com/agent-inject-secret-tls: "pki/issue/grafana-pki"
  vault.hashicorp.com/agent-inject-template-tls: |
    {{ with pkiCert "pki/issue/grafana-pki" "common_name=grafana.monitoring.svc.cluster.local" "ttl=24h" }}
    {{ .Cert }}{{ .CA }}{{ .Key }}
    {{ end }}
  vault.hashicorp.com/agent-inject-command-tls: "/usr/local/bin/split-certs -bundle /vault/secrets/tls -cert /vault/secrets/tls-cert -key /vault/secrets/tls-key -ca /vault/secrets/tls-ca"

nodeSelector:
  kubernetes.io/hostname: gartic-grafana

ingress:
  enabled: false

admin:
  # checkov:skip=CKV_SECRET_6:K8s secret name not a secret value
  existingSecret: "grafana-admin-secret"
  userKey: admin-user
  # checkov:skip=CKV_SECRET_6:K8s secret key name not a secret value
  passwordKey: admin-password

env:
  GF_SECURITY_ADMIN_USER: admin

grafana.ini:
  server:
    protocol: https
    cert_file: /vault/secrets/tls-cert
    cert_key: /vault/secrets/tls-key
  feature_toggles:
    enable: ""
  analytics:
    check_for_updates: false
  plugin_admin:
    enabled: false

service:
  type: NodePort
  nodePort: 30300
  port: 443
  targetPort: 3000

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-operated.monitoring.svc.cluster.local:9090
        access: proxy
        isDefault: true
        jsonData: {}

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboardsConfigMaps:
  default: "grafana-custom-dashboard"

persistence:
  enabled: false

dnsPolicy: ClusterFirstWithHostNet
