serviceAccount:
  create: true
  name: grafana
  automountServiceAccountToken: true

replicas: 1

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/role: "grafana-role"
  vault.hashicorp.com/agent-inject-secret-tls: "pki/issue/grafana-pki"
  vault.hashicorp.com/agent-inject-template-tls: |
    {{ with pkiCert "pki/issue/grafana-pki" "common_name=grafana.monitoring.svc.cluster.local" "ttl=24h" }}
    {{ .Cert }}{{ .CA }}{{ .Key }}
    {{ end }}

nodeSelector:
  kubernetes.io/hostname: gartic-grafana

ingress:
  enabled: false
  # enabled: true
  # ingressClassName: nginx
  # annotations:
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    # nginx.ingress.kubernetes.io/enable-owasp-modsecurity-crs: "true"
  # hosts:
    # - grafana.transcendance.local
  # tls: []

admin:
  existingSecret: "grafana-admin-secret"
  userKey: admin-user
  passwordKey: admin-password

env:
  GF_SECURITY_ADMIN_USER: admin


grafana.ini:
  server:
    protocol: https
    cert_file: /vault/secrets/tls
    cert_key: /vault/secrets/tls


datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: https://prometheus-operated.monitoring.svc.cluster.local:9090
        access: proxy
        isDefault: true
        jsonData:
          tlsSkipVerify: true


# datasources:
  # datasources.yaml:
    # apiVersion: 1
    # datasources:
      # - name: Prometheus
        # type: prometheus
        # url: https://prometheus-operated.monitoring.svc.cluster.local:9090
        # access: proxy
        # isDefault: true
        # jsonData:
          # tlsAuth: true
          # tlsAuthWithCACert: true
          # tlsSkipVerify: false
        # secureJsonData:
          # tlsCACert: $__file{/vault/secrets/tls}
          # tlsClientCert: $__file{/vault/secrets/tls}
          # tlsClientKey: $__file{/vault/secrets/tls}

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboardsConfigMaps:
  default: "grafana-custom-dashboard"

# dashboards: {}
  # default:
    # kubernetes-cluster:
      # gnetId: 15520
      # revision: 10
      # datasource: Prometheus

persistence:
  enabled: false

dnsPolicy: ClusterFirstWithHostNet

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
    scheme: HTTPS

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
    scheme: HTTPS
