apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-web-config
  namespace: monitoring
data:
  web-config.yml: |
    tls_server_config:
      cert_file: /vault/secrets/tls
      key_file: /vault/secrets/tls
