image:
  repository: "437836833311.dkr.ecr.eu-north-1.amazonaws.com/gartic-trans-app"
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: "app.transcendance.local"

vault:
  role: "app-role"
  addr: "http://vault.vault.svc.cluster.local"
  port: "8200"

db:
  host: "172.17.0.1"
  port: "5432"

nodeSelector:
  kubernetes.io/hostname: gartic-master

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
