---
- name: "Directory exist ?"
  file:
    path: "{{ grafana_path }}"
    state: directory
    mode: '0755'

- name: "get docker-compose template"
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ grafana_path }}/docker-compose.yml"
    mode: '0644'
  notify: "Restart Grafana"

- name: "get conf of prometheus"
  template:
    src: "prometheus.yml.j2"
    dest: "{{ grafana_path }}/prometheus.yml"
    mode: '0644'
  notify: "Restart Grafana"

- name: "run docker compose"
  shell: "docker compose up -d"
  args:
    chdir: "{{ grafana_path }}"
  environment:
    GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_pass }}"
    VERSION_PROMETHEUS: "{{ version_prometheus }}"
    VERSION_GRAFANA: "{{ version_grafana }}"
    VERSION_NODE_EXPORTER: "{{ version_node_exporter }}"
    PT_GRAF: "{{ pt_graf }}"
    PT_PROM: "{{ pt_prom }}"
    PT_N_E: "{{ pt_n_e }}"
