---

# a voir si on move ca dans secu os on garde pour test
- name: "Trust K3s network interfaces"
  firewalld:
    zone: trusted
    interface: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - cni0
    - flannel-wg

- name: "Create K3s directory"
  file:
    path: "{{ config_dir }}"
    state: directory
    mode: '0755'

- name: "Copy K3s conf"
  template:
    src: config.yaml.j2
    dest: "{{ config_dir }}/config.yaml"
    mode: '0644'

- name: ".kub dir"
  file:
    path: /home/ec2-user/.kube
    state: directory
    owner: ec2-user
    mode: '0755'

- name: "Installe master"
  shell: |
    curl -sfL https://get.k3s.io | \
    INSTALL_K3S_VERSION={{ version }} \
    sh -s - server \
    --config {{ config_dir }}/config.yaml
  args:
    creates: /usr/local/bin/k3s

- name: "Allow K3s pods to reach PostgreSQL"
  iptables:
    chain: INPUT
    protocol: tcp
    source: "10.42.0.0/16"
    destination_port: "5432"
    jump: ACCEPT
    action: insert

- name: "DNAT PostgreSQL for K3s pods"
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination: "10.42.0.1"
    destination_port: "5432"
    jump: DNAT
    to_destination: "{{ master_private_ip }}:5432"
    action: insert

- name: "Save iptables rules"
  shell: iptables-save > /etc/sysconfig/iptables

- name: "Waiting k3s"
  wait_for:
    path: "{{ token_file }}"
    state: present
    timeout: 60

- name: "Get node toekn"
  slurp:
    src: "{{ token_file }}"
  register: k3s_token

- name: "Set toekn"
  set_fact:
    k3s_node_token: "{{ k3s_token.content | b64decode | trim }}"

- name: "Add k3s to PATH"
  file:
    src: /usr/local/bin/k3s
    dest: /usr/bin/k3s
    state: link

- name: "Wait node"
  shell: k3s kubectl get nodes
  register: nodes
  until: "'Ready' in nodes.stdout"
  retries: 20
  delay: 10

- name: "Copy conf to ec2"
  copy:
    src: "{{ kubeconfig }}"
    dest: /home/ec2-user/.kube/config
    remote_src: yes
    owner: ec2-user
    mode: '0600'

- name: "Install helm"
  shell: |
    curl -sfL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  environment:
    PATH: "/usr/local/bin:/usr/bin:/bin"
  args:
    creates: /usr/local/bin/helm

- name: "symlink helm"
  file:
    src: /usr/local/bin/helm
    dest: /usr/bin/helm
    state: link
    force: yes
    follow: false

- name: "add helm repo"
  shell: |
    /usr/local/bin/helm repo add hashicorp https://helm.releases.hashicorp.com
    /usr/local/bin/helm repo add elastic https://helm.elastic.co
    /usr/local/bin/helm repo add grafana https://grafana.github.io/helm-charts
    /usr/local/bin/helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    /usr/local/bin/helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    /usr/local/bin/helm repo update
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml


- name: "Create namespace app"
  shell: |
    /usr/local/bin/kubectl create namespace app \
      --dry-run=client -o yaml | \
    /usr/local/bin/kubectl apply -f -
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: "Create namespace ingress-nginx"
  shell: |
    /usr/local/bin/kubectl create namespace ingress-nginx \
      --dry-run=client -o yaml | \
       /usr/local/bin/kubectl apply -f -
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: "Create namespace vault"
  shell: |
    /usr/local/bin/kubectl create namespace vault \
      --dry-run=client -o yaml | \
    /usr/local/bin/kubectl apply -f -
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: "Create ECR secret for vault namespace"
  shell: |
    TOKEN=$(aws ecr get-login-password --region eu-north-1)
    /usr/local/bin/kubectl create secret docker-registry ecr-secret \
      --docker-server=437836833311.dkr.ecr.eu-north-1.amazonaws.com \
      --docker-username=AWS \
      --docker-password=$TOKEN \
      --namespace=vault \
      --dry-run=client -o yaml | \
    /usr/local/bin/kubectl apply -f -
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: "Label namespace app for Vault injection"
  shell: |
    /usr/local/bin/kubectl label namespace app \
      vault-injection=enabled --overwrite
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: "Label namespace ingress-nginx for Vault injection"
  shell: |
    /usr/local/bin/kubectl label namespace ingress-nginx \
    vault-injection=enabled --overwrite
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: "Copy ingress-nginx values"
  copy:
    src: "{{ playbook_dir }}/../helm/values/ingress-nginx.yaml"
    dest: /tmp/ingress-nginx-values.yaml
    mode: '0644'

- name: "Copy app chart to master"
  copy:
    src: "{{ playbook_dir }}/../helm/app/"
    dest: /tmp/gartic-app/
    mode: '0644'

- name: "Create ECR image pull secret"
  shell: |
    TOKEN=$(aws ecr get-login-password --region eu-north-1)
    /usr/local/bin/kubectl create secret docker-registry ecr-secret \
      --docker-server=437836833311.dkr.ecr.eu-north-1.amazonaws.com \
      --docker-username=AWS \
      --docker-password=$TOKEN \
      --namespace=app \
      --dry-run=client -o yaml | \
    /usr/local/bin/kubectl apply -f -
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
