---
- name: "Setup AlmaLinux"
  hosts: alma
  become: true
  vars:
    team_ssh_keys:
      - name: kazibuya
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDWF6ELeGn6eP4ZnM+25Vdr0/7QnXAdX1iWv8kjK+EK0zkwz+P24iS1NXXDr2E0bLdQhdRHTmPdiQHP/oLkt8Rd4wyKPW2sMAKzoiSEXMH5rjPKOwmt7mfu6AG9eDblqecyc68rtpSd72aZPcsjmIDq30lLR52Jx38smGDKpp9pW7OAPBgoHOmqXLY1ShTwivl4yjQgRVxGPo8/OJc3xYPnXMsiIaUL/2LWWZnIKoz0MowifnR4Z9iAluDJaa6N9wM3SqcoqH5y/0x72Ak/533ySWdc/6JbYWgS+f0btC+7lmbSKwnch1b32UAAdIhNfxANjX0BvQHXCqivkAG+f7S8OfrdhXxLVtqU1ffel0NsYJ7jxOX8LuCt1uWTBIGYbs/gOQE7V2JyqLgFZ9vQeNe82FlyPj7S8Jq1BX+ZwWgnELfevwbNwXtUzkFr9MiKZyHeWELp5m0pUVMUysktPiOu/gf/d4f9sQXBd0QuhqHdfci190huryuzEeaMh100OytkGylnIlv2uhAj7nE2X51rjSc3EDG5AJt8k8XhtlFs4ZiisD42PYLWXNagPCuqLWttTF1ckuksI8g50X7astn3kCF3mboEMcmepyaXbceeC+rBAh6H1d3Cn030I7WX1+x6VmjPzoFyTxGby1S+6PRRkWQbiGxpr503q25xdLOKAw== namichel@1G4.42angouleme.fr"
      - name: CI
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDi/HFSgv8ARvfVJWAJ4wcWMIQ+xoMgU/LJae5/gF6UUP2bhiJIhVG1DvIA/gVHIrAGmprAgOKIsnYGxxdslaPisODl3yeF2XO5J0UWUH+OkDl2JI+C35QFpAd3LHNpZUlk9ufxu1/Hqu78BC9eLubVj0gtQXW2tKS9qcAJz3wl5Xj1R1yBzA+2uSYMCxT1N6KTybtEaSvupYywIozpgNXqjBT0+Mop8NovOxS8TeKcfhOVEatrwCKYDpHIfmsA/zwGtrBZet9xXgdofD/OUC62Wz14VbRgDhks4dxWiRgcWvkS3CP/PsfEbJFF1rtW4en+VKAnc8OguZoAxtw6LXEUCy46rIyuuvtREu8xGpn9K2JuX9bUpyagllBv1VCsxK08ge22e+y96DKEIBi0YIt0xBALUy9SQl2jWEjc5bstD8NrF2Cgu9E98cUadrY4tUzpieJTl+lxdko00ARR2YuMK7JAt2bTRTh6frYqFD3YdtUfHx0+reyx5hGswHcfbrzZdW6YHxVVEcgWF7cD4JxmFwjsQIAAHIlygxZ/JpazaToWptksTWDz4w+OKBE73zXAL+rfQC2WdE9AUTvCA0Yqby9QHaYi5UYr0JP68sYWX76V8IwCPxuSLc00yfL0NGcu128RIPBrA9C3bO5YtVGU/2D2nZ5DbLpmhEwNFIqwKw== namichel@1F5.42angouleme.fr"
      - name: malignantsystem
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChpVUwzwA5+Wio1CahuTMuIXvjXIi9CKWlfmlJ/Sc1wsQi887Bg0wk3ASQkxiTcyKAQ1IIXONYxx4iNzOl7+nXVmdhJ61fRTwAzPGZgZ+XLkqvyFszeGc98HjTERKTZcbNhDpS9vXKLY6PUF3m3DQkYIglaAhkZbEk/g9CM5mWMi8zBznvxrzpl0Jy63P4qqzAg+4TNiWafrf9xbCxMPNl1Oz030bYIrvl+tsNcaSwc+AzP5ODZXK/VBTutdKN29MUee25bwmDrEBK3bJTG+D2V1wlmRkwu+c5SU+kHEa/j+D79PPNKMrQBPMyFHze61mjlqtFoU7SAuVxfLcCf2hldK/Cf07qht6OVx66fuQA+nvLkH32Q9ql3Gc99Y7wICTGeL3btcm1jTAbvWRD6XaqAyHo2hEvgdo5MEwO8PO8poMi+bsXdMy+ZWUf2XhekgfhBkxfQJEnCe+KsB5uuO/9TmS98tusy2SKACo8M6TjOIIZmOiFcCfPKsdm9OuCseE= pmilner-@2F3.42angouleme.fr"
  tasks:

    - name: "Update OS"
      dnf:
        name: "*"
        state: latest
        update_cache: true

    - name: "EPEL"
      dnf:
        name: "epel-release"
        state: present

    - name: "Get packages"
      dnf:
        name:
          - "git"
          - "htop"
          - "curl"
          - "wget"
          - "tar"
          - "pip"
        state: present

    - name: "Rename"
      hostname:
        name: gartic-server

    - name: "Proccess Security_OS"
      include_role:
        name: security_os

    - name: "Proccess Docker Install"
      include_role:
        name: docker_install

    - name: "Load Vault secrets"
      include_vars:
        file: "{{ playbook_dir }}/secrets.yml"
      # ignore_errors: true
      when: lookup('fileglob', playbook_dir + '/secrets.yml') != []

    - name: "Vault"
      include_role:
        name: security_vault
# 
    # - name: "GO Server"
      # include_role:
        # name: go-server

    - name: "Gathering Facts"
      debug:
        msg:
          - "Name: {{ ansible_hostname }}"
          - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Total uptime: {{ (ansible_uptime_seconds / 3600) | round(2) }} heures"
          - "Deploy by: {{ deploy_user | default('manual') }}"
