name: Security

on:
  push:
    branches: ['**']
    tags-ignore: ['v*']
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read
  checks: write

jobs:
  checkov:
    name: Checkov IaC Scan
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
    steps:
      - uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          soft_fail: true
          output_format: junitxml
          output_file_path: console

      - name: Upload Checkov results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: checkov-report
          path: '**/results_junitxml.xml'

      - name: Publish Checkov Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/results_junitxml.xml'
          detailed_summary: true
          check_name: "Checkov Security Report"

  trivy:
    name: Trivy Scan
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          format: table
          output: trivy-results.txt
          exit-code: 0

      # - name: Upload Trivy results
        # uses: actions/upload-artifact@v4
        # if: always()
        # with:
          # name: trivy-report
          # path: trivy-results.xml

      - name: Publish Trivy Report
        # uses: mikepenz/action-junit-report@v4
        if: always()
        # with:
          # report_paths: trivy-results.xml
          # detailed_summary: true
          # check_name: "Trivy Security Report"
        run: |
          echo "Trivy Scan Results" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat trivy-results.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY


  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build SonarQube stage
        run: |
          docker build \
            --target sonarqube \
            --build-arg GO_ARCH=amd64 \
            -t sonar-scan \
            ./go-server

      - name: Run SonarQube scan
        run: |
          docker run --rm \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            sonar-scan \
            sonar-scanner \
              -Dsonar.token=${{ secrets.SONAR_TOKEN }}
