package main

import (
	"context"
	//"encoding/json"
	"log"
	"fmt"
	"net/http"
	"os"
	// following two are for lobby generation
	"math/rand"
	//"math/rand/v2"
	"time"
	// "sync"

	"github.com/gin-gonic/gin"
	//"github.com/jackc/pgx/v5"
	vault "github.com/hashicorp/vault/api"
	awsauth "github.com/hashicorp/vault/api/auth/aws"
	"github.com/gorilla/websocket"
)

type Config struct {
	APIKey     string `json:"api_key"`
	DBPassword string `json:"db_password"`
	JWTSecret  string `json:"jwt_secret"`
}

type LobbySettings struct {
	Rounds int `json:"rounds"`
	Timer int `json:"timer"`
}

type CreateLobbyRequest struct {
	HostID string `json:"hostId"`
	Settings LobbySettings `json:"settings"`
}

type CreateLobbyResponse struct {
	LobbyCode string `json:"lobbyCode"`
}

var config Config

func generateLobbyCode(length int) string {
	const charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" // Removed the numeric arguements as 0123456789
	seededRand := rand.New(rand.NewSource(time.Now().UnixNano()))
	
	ret := make([]byte, length)
	for i := range ret {
		ret[i] = charset[seededRand.Intn(len(charset))]
	}

	return string(ret)
}

func createLobby(c *gin.Context) {
	// var req CreateLobbyRequest
// 
	// if err := c.ShouldBindJSON(&req); err != nil {
		// c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid request payload: " + err.Error()})
		// return
	// }

	lobbyCode := generateLobbyCode(6)
	
	//fmt.Println("The generated lobby code is: " + lobbyCode) //debug command

	c.JSON(http.StatusOK, CreateLobbyResponse{
		LobbyCode: lobbyCode,
	})
}

func pong(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"message": "pong",
	})
}

func health(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
			"status": "ok",
	})
}

func vaultstatus(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"api_key_loaded" : config.APIKey != "",
		"db_password_loaded" : config.DBPassword != "",
		"jwt_secret_loaded" : config.JWTSecret != "",
	})
}

/*
The message structure contains the json information to be sent / received by the websocket for room generation
type: state before / after generation of the room code
code: room code
omitempty: omits empty strings, lowering network traffic

*/

type Message struct {
    Type   string `json:"type"`
    Code   string `json:"code,omitempty"`
    Reason string `json:"reason,omitempty"`
}

func socketLogic(conn *websocket.Conn) {
    for {
        var msg Message
        // Read JSON from the frontend
        err := conn.ReadJSON(&msg)
        if err != nil {
            break // Stop reading and fully disconnect the socket
        }

		fmt.Println("type: " + msg.Type + " code: " + msg.Code + " reason " + msg.Reason)

        if msg.Type == "create_room" {
            // Generate the code
            newCode := generateLobbyCode(6) 
            
			fmt.Println("Code generated by the backend: " + newCode) // I can't show this in the inspect element console, that needs to be implemented in the javascript

            // Store it in the DB 
            
            // Send the response back
            response := Message{
                Type: "room_created",
                Code: newCode,
            }
            conn.WriteJSON(response)
        }
    }
}

/*
	Gorilla structure needed to switch the http protocol to a websocket
	has a read / write buffer, not unlike ft_irc, it can store incomplete in and out data
	checkOrigin makes sure that the origin of the request is on our own domain, currently it
		accepts all origins, but as websockets are vulnerable to cross site websocket hijacking,
			we need to set it to something more secure later.
*/

var upgrader = websocket.Upgrader{
    ReadBufferSize:  1024,
    WriteBufferSize: 1024,
    // Allow all origins for development; be stricter in production!
    CheckOrigin: func(r *http.Request) bool {
        return true
    },
}

/*
	upgrades the http protocol to a websocket, when its "done" it closes the connection
	"done" is defined by either the webpage being closed, or the websocket handler returned
*/

func handleWebsocket(c *gin.Context) {
	// we upgrade the 
	conn, err := upgrader.Upgrade(c.Writer, c.Request, nil )
	if err != nil {
		return 
	}
	defer conn.Close()
	socketLogic(conn)
}

func main() {
	fmt.Println("~o~ This project was brought to you with hate by pmilner- mforest- namichel & lviravon! ~o~")
	fmt.Println(" ~~ Starting transcendence backend... ~~")

	
	// if err := loadSecretsFromVault(); err != nil {
	// 	log.Fatalf("Failed to load secrets from Vault: %v", err)
	// }
	// Gin router with default "middleware"
	router := gin.Default();
	// gin.SetMode(gin.ReleaseMode)
	// https://github.com/gin-gonic/gin/blob/master/docs/doc.md#dont-trust-all-proxies 
	// define a port, ie 443 / 80 so we can connect over https / http

	// router.StaticFile("/", "./static/index.html")
	router.Static("/assets", "./static/assets")
	router.StaticFile("/favicon.ico", "./static/favicon.ico")
	router.NoRoute(func(c *gin.Context) {
		c.File("./static/index.html")
	})


	// GET endpoint in the router
	router.GET("/ping", pong)
	router.GET("/health", health)
	router.GET("/api/config", vaultstatus)
	router.GET("/ws", handleWebsocket)
	//router.POST("/api/rooms", createLobby)
	router.POST("/api/player", handleLogin)

	// get the port defined in the environment variables, if theres fuckall, 8080

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
		
	if err := router.Run(":" + port); err != nil {
		log.Fatalf("failed to run server: %v", err)	
	}
}

func loadSecretsFromVault() error {
	vaultAddr := os.Getenv("VAULT_ADDR")
	if vaultAddr == "" {
		vaultAddr = "http://vault:8200"
	}

	cfg := vault.DefaultConfig()
	cfg.Address = vaultAddr

	client, err := vault.NewClient(cfg)
	if err != nil {
		return fmt.Errorf("unable to create vault client: %w", err)
	}

	// Check for local dev/test token first
    if token := os.Getenv("VAULT_TOKEN"); token != "" {
        client.SetToken(token)
        log.Println("Using direct VAULT_TOKEN (Local Dev/Test Mode)")
    } else {
        // Fallback to Production AWS IAM Auth
        awsAuth, err := awsauth.NewAWSAuth(
            awsauth.WithRole("app-role"),
        )
        if err != nil {
            return fmt.Errorf("unable to create AWS auth: %w", err)
        }

        authInfo, err := client.Auth().Login(context.Background(), awsAuth)
        if err != nil {
            return fmt.Errorf("vault login failed: %w", err)
        }
        if authInfo == nil {
            return fmt.Errorf("no auth info returned")
        }
        log.Println("Authenticated via AWS IAM")
    }

    // ... continue to your KV v2 secret reading ...

	// Lecture des secrets KV v2
	kv, err := client.KVv2("secret").Get(context.Background(), "app/config")
	if err != nil {
		return fmt.Errorf("failed to read secrets: %w", err)
	}

	config.APIKey = kv.Data["api_key"].(string)
	config.DBPassword = kv.Data["db_password"].(string)
	config.JWTSecret = kv.Data["jwt_secret"].(string)

	fmt.Println("this is wicked insecure, remove this line before moving further on in prod " + config.APIKey + " " + config.DBPassword + " " + config.JWTSecret )

	log.Println("Secrets loaded from Vault successfully")
	return nil
}
