package main

import (
	"fmt"
	"context"
	"main.go/gamemanager"
	"math/rand/v2"
	"net/http"
	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
	"github.com/jackc/pgx/v5/pgxpool"
	
)

func socketLogic(conn *websocket.Conn, db *pgxpool.Pool, hub *gamemanager.Hub) {
	var currentUsername string
	for {
		var msg Message
		// Read JSON from the frontend
		err := conn.ReadJSON(&msg)
		if err != nil {
			break // Stop reading and fully disconnect the socket
		}

		fmt.Println("type: " + msg.Type + " code: " + msg.Code + " reason " + msg.Reason)

		if msg.Type == "authenticate" {
			UserToken := msg.Token
            fmt.Println("WS authenticated for player: " + UserToken)
			continue
		}

		if msg.Type == "create_room" {
			// Generate the code
			newCode := hub.CreateRoom() // TODO add room too db 
			
			fmt.Println("Code generated by the backend: " + newCode.ID) // I can't show this in the inspect element console, that needs to be implemented in the javascript

			// Store it in the DB 
			query := "INSERT INTO rooms (room_code, created_at) VALUES ($1, NOW())"

			_, err := db.Exec(context.Background(), query, newCode.ID)
			if err != nil {
				fmt.Println("Failed to insert new values into tables: %v", err)
				response := Message{
					Type: "create_denied",
					Reason: "Failed to create the room.",
				}
				// Send the response back
				conn.WriteJSON(response)
			} else {
				response := Message{
			    	Type: "room_created",
			    	Code: newCode.ID,
				}
				// Send the response back
				conn.WriteJSON(response)
			}
		}
		if (msg.Type == "join_room") {
			room, err := hub.GetRoom(msg.Code)
			if (err != nil) {
				response := (Message{
					Type: "join_denied",
					Reason: "Invalid Room",
				})
				conn.WriteJSON(response)
				continue;
			}
			playerID := rand.IntN(len(currentUsername) * 100) // NOTE tmp ID
			err = room.AddPlayer(playerID, currentUsername); // TODO set correct ID
			
			if (err != nil) {
				response := (Message{
					Type: "join_denied",
					Reason: err.Error(),
				})
				conn.WriteJSON(response)
				continue;
			}


			response := (Message{
				Type: "join_success",
				Code: room.ID,
			})
			conn.WriteJSON(response)
		}
	}
}

/*
	Gorilla structure needed to switch the http protocol to a websocket
	has a read / write buffer, not unlike ft_irc, it can store incomplete in and out data
	checkOrigin makes sure that the origin of the request is on our own domain, currently it
		accepts all origins, but as websockets are vulnerable to cross site websocket hijacking,
			we need to set it to something more secure later.
*/

var upgrader = websocket.Upgrader{
	ReadBufferSize:  1024,
	WriteBufferSize: 1024,
	// Allow all origins for development; be stricter in production!
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
}

/*
	upgrades the http protocol to a websocket, when its "done" it closes the connection
	"done" is defined by either the webpage being closed, or the websocket handler returned
*/

func handleWebsocket(c *gin.Context, db *pgxpool.Pool, hub *gamemanager.Hub) {
	// we upgrade the connection to a websocket
	// MALO SENDS THE TOKEN WITH SEND, NEEDS TO BE CHECKED.


	
	conn, err := upgrader.Upgrade(c.Writer, c.Request, nil )
	if err != nil {
		return 
	}
	defer conn.Close()
	socketLogic(conn, db, hub)
}
