package main

import (
	"fmt"

	"net/http"
	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
)

func socketLogic(conn *websocket.Conn) {
	var currentUsername string
	for {
		var msg Message
		// Read JSON from the frontend
		err := conn.ReadJSON(&msg)
		if err != nil {
			break // Stop reading and fully disconnect the socket
		}

		fmt.Println("type: " + msg.Type + " code: " + msg.Code + " reason " + msg.Reason)

		if msg.Type == "authenticate" {
			currentUsername = msg.Token
            fmt.Println("WS authenticated for player: " + currentUsername)
			continue
		}

		if msg.Type == "create_room" {
			// Generate the code
			newCode := generateLobbyCode(6) 

			fmt.Println("Code generated by the backend: " + newCode) // I can't show this in the inspect element console, that needs to be implemented in the javascript

			// Store it in the DB 

			// Send the response back
			response := Message{
			    Type: "room_created",
			    Code: newCode,
			}
			conn.WriteJSON(response)
		}
	}
}

/*
	Gorilla structure needed to switch the http protocol to a websocket
	has a read / write buffer, not unlike ft_irc, it can store incomplete in and out data
	checkOrigin makes sure that the origin of the request is on our own domain, currently it
		accepts all origins, but as websockets are vulnerable to cross site websocket hijacking,
			we need to set it to something more secure later.
*/

var upgrader = websocket.Upgrader{
	ReadBufferSize:  1024,
	WriteBufferSize: 1024,
	// Allow all origins for development; be stricter in production!
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
}

/*
	upgrades the http protocol to a websocket, when its "done" it closes the connection
	"done" is defined by either the webpage being closed, or the websocket handler returned
*/

func handleWebsocket(c *gin.Context) {
	// we upgrade the 
	conn, err := upgrader.Upgrade(c.Writer, c.Request, nil )
	if err != nil {
		return 
	}
	defer conn.Close()
	socketLogic(conn)
}
